spring.application.name=Usermangement
spring.datasource.url=jdbc:mariadb://localhost:3306/tax_principle_uat
spring.datasource.username=springuser
spring.datasource.password=StrongPassword123
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
app.jwt.secret=loYt2p+WCPcnMAjzHPjsTc+0jxaYYMTZqjQJEe/YZrbb83ydYFXMUtZbEIXgYSiOvos122+2chFBXPQC2RPstg==
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000



